---
title: "Appendix 4: DLMs and GAMs for Lake Washington data"
format: pdf
editor: visual
---

# Appendix 4: DLMs and GAMs for Lake Washington data

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,  
  error = FALSE,    
  message = FALSE
)
```

```{r}
#install.packages('marssTMB', repos = c('https://atsa-es.r-universe.dev', #'https://cloud.r-project.org'))
library(MARSS)
library(mgcv)
library(dplyr)
library(forecast)
library(ggplot2)
library(lubridate)
library(marssTMB)
library(paletteer)
library(ggpubr)
library(grid)
col<-paletteer_d("nationalparkcolors::Everglades")

```

## Data

```{r}
dat_lakewa <- readRDS("data_for_lakeWA_example.rds")
dat_aksalmon <- readRDS("data_for_AK_salmon_example.rds")

# renaming
dat_lakewa <- dplyr::rename(dat_lakewa, 
                            response = y_adj,
                            driver = lagged_zp)
dat_aksalmon <- dplyr::rename(dat_aksalmon,
                              response = salmon_DFA,
                              driver = z_sst, 
                              date = year)
```

## DLM with time-varying intercepts and time-varying slopes

Define the model – this block is basically copied from the MARSS book (salmon survival case study). First for the Lake WA example:

```{r}
dat <- dat_lakewa
m <- 2
TT <- nrow(dat)
B <- diag(m)  ## 2x2; Identity
U <- matrix(0, nrow = m, ncol = 1)  ## 2x1; both elements = 0
Q <- matrix(list(0), m, m)  ## 2x2; all 0 for now
diag(Q)[1] <- c("q.alpha")
diag(Q)[2] <- c("q.beta")
Z <- array(NA, c(1, m, TT))  ## NxMxT; empty for now
Z[1, 1, ] <- rep(1, TT)  ## Nx1; 1's for intercept
Z[1, 2, ] <- dat$driver  ## Nx1; predictor variable
A <- matrix(0)  ## 1x1; scalar = 0
R <- matrix("r")  ## 1x1; scalar = r
## only need starting values for regr parameters
inits_list <- list(x0 = matrix(c(0, 0), nrow = m))
## list of model matrices & vectors
mod_list <- list(B = B, U = U, Q = Q, Z = Z, A = A, R = R)
# convert response to matrix
dat_mat <- matrix(dat$response, nrow = 1)
# fit the model -- crank up the maxit to ensure convergence
dlm_lakewa_1 <- MARSS(dat_mat, inits = inits_list, model = mod_list,
               control = list(maxit=4000), method="TMB")

# Fit a second model with just time-varying slope
diag(Q)[1] <- 1e-10
mod_list <- list(B = B, U = U, Q = Q, Z = Z, A = A, R = R)
dlm_lakewa_2 <- MARSS(dat_mat, inits = inits_list, model = mod_list,
               control = list(maxit=4000), method="TMB")
```

Now for the AK salmon example

```{r}
dat <- dat_aksalmon
m <- 2
TT <- nrow(dat)
B <- diag(m)  ## 2x2; Identity
U <- matrix(0, nrow = m, ncol = 1)  ## 2x1; both elements = 0
Q <- matrix(list(0), m, m)  ## 2x2; all 0 for now
diag(Q)[1] <- c("q.alpha")
diag(Q)[2] <- c("q.beta")
Z <- array(NA, c(1, m, TT))  ## NxMxT; empty for now
Z[1, 1, ] <- rep(1, TT)  ## Nx1; 1's for intercept
Z[1, 2, ] <- dat$driver  ## Nx1; predictor variable
A <- matrix(0)  ## 1x1; scalar = 0
R <- matrix("r")  ## 1x1; scalar = r
## only need starting values for regr parameters
inits_list <- list(x0 = matrix(c(0, 0), nrow = m))
## list of model matrices & vectors
mod_list <- list(B = B, U = U, Q = Q, Z = Z, A = A, R = R)
# convert response to matrix
dat_mat <- matrix(dat$response, nrow = 1)
# fit the model -- crank up the maxit to ensure convergence
dlm_aksalmon_1 <- MARSS(dat_mat, inits = inits_list, model = mod_list,
               control = list(maxit=4000), method="TMB")

# Fit a second model with just time-varying slope
diag(Q)[1] <- 1e-10
mod_list <- list(B = B, U = U, Q = Q, Z = Z, A = A, R = R)
dlm_aksalmon_2 <- MARSS(dat_mat, inits = inits_list, model = mod_list,
               control = list(maxit=4000), method="TMB")
```

## Time varying models with MGCV

```{r}
K_WA <- round(0.99*nrow(dat_lakewa))
K_AK <- round(0.99*nrow(dat_aksalmon))
dat_lakewa$n_date <- seq(1,nrow(dat_lakewa))
gam_lakewa_1 <- gam(response ~ s(n_date,k=K_WA) + s(n_date, by = driver, bs = "gp",k=K_WA), data = dat_lakewa)
gam_lakewa_2 <- gam(response ~ s(n_date, by = driver, bs = "gp",k=K_WA), data = dat_lakewa)

dat_aksalmon$n_date <- seq(1,nrow(dat_aksalmon))
gam_aksalmon_1 <- gam(response ~ s(n_date,k=K_AK) + s(n_date, by = driver, bs = "gp",k=K_AK), data = dat_aksalmon)
gam_aksalmon_2 <- gam(response ~ s(n_date, by = driver, bs = "gp",k=K_AK), data = dat_aksalmon)

# extract the smooth estimates with SEs to compare to DLM
plot_1 <- plot(gam_lakewa_1, seWithMean = TRUE, n = nrow(dat_lakewa))
plot_2 <- plot(gam_lakewa_2, seWithMean = TRUE, n = nrow(dat_lakewa))

plot_3 <- plot(gam_aksalmon_1, seWithMean = TRUE, n = nrow(dat_aksalmon))
plot_4 <- plot(gam_aksalmon_2, seWithMean = TRUE, n = nrow(dat_aksalmon))
```

```{r}
summary(gam_lakewa_2)

dat_aksalmon$date <- paste0(dat_aksalmon$date,"-01-01")

coef_dlm_lakeWA1 <- data.frame(date = dat_lakewa$date, 
                        int_est = dlm_lakewa_1$states[1,],
                        int_se = dlm_lakewa_1$states.se[1,],
                        slope_est = dlm_lakewa_1$states[2,],
                        slope_se = dlm_lakewa_1$states.se[2,],
                        time_varying = "Intercept + slope",
                        dataset = "Lake Washington : DLM")
coef_dlm_lakeWA2 <- data.frame(date = dat_lakewa$date, 
                        int_est = 0,
                        int_se = 0,
                        slope_est = dlm_lakewa_2$states[2,],
                        slope_se = dlm_lakewa_2$states.se[2,],
                        time_varying = "Slope",
                        dataset = "Lake Washington : DLM")
coef_dlm_AK1 <- data.frame(date = dat_aksalmon$date,
                        int_est = dlm_aksalmon_1$states[1,],
                        int_se = dlm_aksalmon_1$states.se[1,],
                        slope_est = dlm_aksalmon_1$states[2,],
                        slope_se = dlm_aksalmon_1$states.se[2,],
                        time_varying = "Intercept + slope",
                        dataset = "Alaska salmon : DLM")
coef_dlm_AK2 <- data.frame(date = dat_aksalmon$date,
                        int_est = 0,
                        int_se = 0,
                        slope_est = dlm_aksalmon_2$states[2,],
                        slope_se = dlm_aksalmon_2$states.se[2,],
                        time_varying = "Slope",
                        dataset = "Alaska salmon : DLM")


coef_gam_lakeWA1 <- data.frame(date = dat_lakewa$date, 
                        int_est = plot_1[[1]]$fit,
                        int_se = plot_1[[1]]$se,
                        slope_est = plot_1[[2]]$fit,
                        slope_se = plot_1[[2]]$se,
                        time_varying = "Intercept + slope",
                        dataset = "Lake Washington : GAM")
coef_gam_lakeWA2 <- data.frame(date = dat_lakewa$date, 
                        int_est = 0,
                        int_se = 0,
                        slope_est = plot_2[[1]]$fit,
                        slope_se = plot_2[[1]]$se,
                        time_varying = "Slope",
                        dataset = "Lake Washington : GAM")
coef_gam_AK1 <- data.frame(date = dat_aksalmon$date,
                        int_est = plot_3[[1]]$fit,
                        int_se = plot_3[[1]]$fit,
                        slope_est = plot_3[[2]]$fit,
                        slope_se = plot_3[[2]]$fit,
                        time_varying = "Intercept + slope",
                        dataset = "Alaska salmon : GAM")
coef_gam_AK2 <- data.frame(date = dat_aksalmon$date,
                        int_est = 0,
                        int_se = 0,
                        slope_est = plot_4[[1]]$fit,
                        slope_se = plot_4[[1]]$se,
                        time_varying = "Slope",
                        dataset = "Alaska salmon : GAM")

coefs <- rbind(coef_dlm_lakeWA1, coef_dlm_lakeWA2, coef_dlm_AK1, coef_dlm_AK2,
               coef_gam_lakeWA1, coef_gam_lakeWA2, coef_gam_AK1, coef_gam_AK2)

annotate_Slope<-data.frame(label=c("A.", "B.","E.", "F"),
                       date=c(1975,1975,dat_lakewa$date[25],dat_lakewa$date[25]),
                       y=c(7.5,10,4.5,7.75), time_varying=c("slope","slope","slope","slope"))

slope_panel <-ggplot(coefs, aes(date, slope_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=slope_est-2*slope_se, ymax = slope_est+2*slope_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab(" ") + 
  xlab("") + theme_classic() + 
  ggtitle("Slope")+
  #ylim(c(-5,11))+
  facet_wrap(~ dataset, scale="free") + 
  #scale_color_viridis_d(option="magma",begin=0.2, end=0.8, name = "Time-varying") + 
  #scale_fill_viridis_d(option="magma",begin=0.2, end=0.8, name = "Time-varying") + 
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  guides(fill="none",colour="none",lty="none")+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5)
  )
slope_panel 
int_panel <- ggplot(coefs, aes(date, int_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=int_est-2*int_se, ymax = int_est+2*int_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab(" ") + 
  xlab("") + theme_classic() + 
  facet_wrap(~ dataset, scale="free") + 
  ggtitle("Intercept")+
  #ylim(-20,10.5)+
  #scale_color_viridis_d(option="magma",begin=0.2, end=0.8, name = "Time-varying") + 
  #scale_fill_viridis_d(option="magma",begin=0.2, end=0.8, name = "Time-varying") + 
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5)
  )
int_panel


Fig4<-ggarrange(slope_panel,int_panel, nrow=1,ncol=2, widths=c(1,1.25))
annotate_figure(Fig4, bottom = textGrob("Year", gp = gpar(cex = 1)))


ggsave("Figure_4_dlmgam_comparison.png", height = 7, width = 11)

ggsave("Figure_5_dlmgam_comparison.pdf", height = 7, width = 11)

#ggsave("Figure_2_dlmgam_comparison.png", height = 7, width = 7)
```

```{r}
panel_a<-ggplot(coefs%>%filter(dataset=="Alaska salmon : DLM"), aes(date, slope_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=slope_est-2*slope_se, ymax = slope_est+2*slope_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
  xlab("") + theme_classic() +
  ylim(c(-3.5,11))+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  guides(fill="none",colour="none",lty="none")+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5)
  )

panel_b<-ggplot(coefs%>%filter(dataset=="Alaska salmon : GAM"), aes(date, slope_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=slope_est-2*slope_se, ymax = slope_est+2*slope_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
  xlab("") + theme_classic() +
  ylim(c(-3.5,11))+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  guides(fill="none",colour="none",lty="none")+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5)
  )

panel_e <- ggplot(coefs%>%filter(dataset=="Lake Washington : DLM"), aes(date, slope_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=slope_est-2*slope_se, ymax = slope_est+2*slope_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
  xlab("") + theme_classic() +
  #ylim(c(-1.5,5.1))+
   ylim(c(-7,8))+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  guides(fill="none",colour="none",lty="none")+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5)
  )

panel_f <-ggplot(coefs%>%filter(dataset=="Lake Washington : GAM"), aes(date, slope_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=slope_est-2*slope_se, ymax = slope_est+2*slope_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
  xlab("") + theme_classic() +
  #ylim(c(-1.5,5.1))+
   ylim(c(-7,8))+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  guides(fill="none",colour="none",lty="none")+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5)
  )


fig_slope=ggarrange(panel_a, panel_b, panel_e,panel_f, nrow=2,ncol=2,
           labels = c("A.", "B.", "E.", "F."))
fig_slope_y<-annotate_figure(fig_slope, left = textGrob("Time-varying slope",rot=90,gp = gpar(cex = 1)))



panel_c<-ggplot(coefs%>%filter(dataset=="Alaska salmon : DLM"), aes(date, int_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=int_est-2*int_se, ymax = int_est+2*int_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
  xlab("") + theme_classic() + 
  ylim(-16,11)+
    guides(fill="none",colour="none",lty="none")+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5)
  )

panel_d<-ggplot(coefs%>%filter(dataset=="Alaska salmon : GAM"), aes(date, int_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=int_est-2*int_se, ymax = int_est+2*int_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
  xlab("") + theme_classic() + 
  ylim(-16,11)+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
      guides(fill="none",colour="none",lty="none")+

  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5)
  )

panel_g<-ggplot(coefs%>%filter(dataset=="Lake Washington : DLM"), aes(date, int_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=int_est-2*int_se, ymax = int_est+2*int_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
  xlab("") + theme_classic() + 
    ylim(-8.5,4.5)+
    guides(fill="none",colour="none",lty="none")+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5)
  )
panel_h<-ggplot(coefs%>%filter(dataset=="Lake Washington : GAM"), aes(date, int_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=int_est-2*int_se, ymax = int_est+2*int_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
  xlab("") + theme_classic() + 
  ylim(-8.5,4.5)+
    guides(fill="none",colour="none",lty="none")+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5)
  )


CG<-ggarrange(panel_c, panel_g, nrow=2,ncol=1,
           labels = c("C.", "G."))%>%
annotate_figure(top = textGrob("DLM",gp = gpar(cex = 1)))

DH<-ggarrange(panel_d, panel_h,nrow=2,ncol=1,
           labels = c("D.", "H."))%>%
annotate_figure(top = textGrob("GAM",gp = gpar(cex = 1)))
intercepts<-ggarrange(CG, DH,nrow=1,ncol=2)%>%
annotate_figure(left = textGrob("Intercept Estimates",rot=90,gp = gpar(cex = 1)))

AE<-ggarrange(panel_a, panel_e, nrow=2,ncol=1,
           labels = c("A.", "E."))%>%
annotate_figure(top = textGrob("DLM",gp = gpar(cex = 1)))
BF<-ggarrange(panel_b, panel_f,nrow=2,ncol=1,
           labels = c("B.", "F."))%>%
annotate_figure(top = textGrob("GAM",gp = gpar(cex = 1)))
slopes<-ggarrange(AE, BF,nrow=1,ncol=2)%>%
annotate_figure(left = textGrob("Slope Estimates",rot=90,gp = gpar(cex = 1)))




```

```{r}
coefs<-coefs%>%mutate(year=as.numeric(format(date, "%Y")))

annotateGoA<-data.frame(label=c("High AL \n  Variability",
                                "Low AL \n Variability",
                                "Marine \n HW"),
                        date=c(1975, 2000,2019),
                        y=c(10,10,10), Anomalies=c("z_sst","z_sst","z_sst"))


annotateWA<-data.frame(label=c("Sewage \n Inputs", "Water \n Treatment"),
                       date=c(dat_lakewa$date[25],dat_lakewa$date[100]),
                       y=c(4,4), TimeSeries=c("TP","TP"))


panel_a<-ggplot(coefs%>%filter(dataset=="Alaska salmon : DLM"), aes(x=year, y=int_est)) + 
  geom_ribbon(aes(ymin=int_est-2*int_se, ymax = int_est+2*int_se, group = time_varying, fill=time_varying, col=time_varying), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying, group = time_varying,  col=time_varying)) + 
  ylab("Intercept Estimate") + 
  ggtitle("DLM")+
  xlab("") + theme_classic() + 
  ylim(-16,11)+
  #xlim(1965,2030)+
  geom_vline(xintercept=c(1989,2014), lty=c(2,2),col='grey')+
  geom_text(data=annotateGoA, aes(x = date, y = y, 
                                  label = label),  
            col='black',fontface = "italic",cex=2.6)+
  geom_hline(yintercept=0, lty=3,col=col[5])+

  guides(fill="none",colour="none",lty="none")+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5),axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank()
  )

panel_e<-ggplot(coefs%>%filter(dataset=="Alaska salmon : DLM"), aes(year, slope_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=slope_est-2*slope_se, ymax = slope_est+2*slope_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("Slope Estimate") + 
  xlab("") + theme_classic() +
  ylim(c(-3.5,11))+
  geom_vline(xintercept=c(1989,2014), lty=c(2,2),col='grey')+

  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  guides(fill="none",colour="none",lty="none")+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5)
  )

panel_f<-ggplot(coefs%>%filter(dataset=="Alaska salmon : GAM"), aes(year, slope_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=slope_est-2*slope_se, ymax = slope_est+2*slope_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
  geom_vline(xintercept=c(1989,2014), lty=c(2,2),col='grey')+

  xlab("") + theme_classic() +
  ylim(c(-3.5,11))+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  guides(fill="none",colour="none",lty="none")+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5),
    axis.title.y=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()
  )

panel_g <- ggplot(coefs%>%filter(dataset=="Lake Washington : DLM"), aes(date, slope_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=slope_est-2*slope_se, ymax = slope_est+2*slope_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
    geom_vline(xintercept=dat_lakewa$date[56], lty=2,col='grey')+

  xlab("") + theme_classic() +
  #ylim(c(-1.5,5.1))+
  ylim(c(-7,8))+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  guides(fill="none",colour="none",lty="none")+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5)
  )

panel_h <-ggplot(coefs%>%filter(dataset=="Lake Washington : GAM"), aes(date, slope_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=slope_est-2*slope_se, ymax = slope_est+2*slope_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") +
    geom_vline(xintercept=dat_lakewa$date[56], lty=2,col='grey')+

  xlab("") + theme_classic() +
  #ylim(c(-1.5,5.1))+
  ylim(c(-7,8))+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  guides(fill="none",colour="none",lty="none")+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5),
    axis.title.y=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()
  )


fig_slope=ggarrange(panel_e, panel_f, panel_g,panel_h, nrow=1,ncol=4,
                    labels = c("E.", "F.", "G.", "H."))


fig_slope_y<-annotate_figure(fig_slope, left = textGrob("Time-varying slope",rot=90,gp = gpar(cex = 1)))






panel_b<-ggplot(coefs%>%filter(dataset=="Alaska salmon : GAM"), aes(year, int_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=int_est-2*int_se, ymax = int_est+2*int_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
  xlab("") + theme_classic() + 
  ylim(-16,11)+
  ggtitle("GAM")+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  guides(fill="none",colour="none",lty="none")+
  geom_vline(xintercept=c(1989,2014), lty=c(2,2),col='grey')+

  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5),axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    axis.title.y=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()
  )

panel_c<-ggplot(coefs%>%filter(dataset=="Lake Washington : DLM"), aes(date, int_est)) + 
  geom_ribbon(aes(ymin=int_est-2*int_se, ymax = int_est+2*int_se, group = time_varying, fill=time_varying, col=time_varying), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying, group = time_varying, fill=time_varying, col=time_varying)) + 
  ylab("") + 
  xlab("") + theme_classic() + 
  ylim(-8.5,4.5)+
  geom_vline(xintercept=dat_lakewa$date[56], lty=2,col='grey')+
  geom_text(data=annotateWA, aes(x = date, y = y, 
                                label = label),  col='black',fontface = "italic", cex=2.8)+

  ggtitle("DLM")+
  guides(fill="none",colour="none",lty="none")+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5),axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank()
  )

panel_d<-ggplot(coefs%>%filter(dataset=="Lake Washington : GAM"), aes(date, int_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=int_est-2*int_se, ymax = int_est+2*int_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
  xlab("") + theme_classic() + 
    geom_vline(xintercept=dat_lakewa$date[56], lty=2,col='grey')+

  ylim(-8.5,4.5)+
  ggtitle("GAM")+
  guides(fill="none",colour="none",lty="none")+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5),axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    axis.title.y=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()
  )

fig_int=ggarrange(panel_a, panel_b, panel_c,panel_d, nrow=1,ncol=4,
                    labels = c("A.", "B.", "C.", "D."))


fig_left=ggarrange(panel_a, panel_b, panel_e,panel_f, nrow=2,ncol=2,
                  labels = c("A.", "B.", "E.", "F."), widths=c(1.25,1))%>%
  annotate_figure(top = textGrob("Gulf of Alaska Dataset",gp = gpar(cex = 1)))


fig_right=ggarrange(panel_c, panel_d, panel_g,panel_h, nrow=2,ncol=2,
                   labels = c("C.", "D.", "G.", "H."), widths=c(1.25,1))%>%
  annotate_figure(top = textGrob("Lake WA Dataset",gp = gpar(cex = 1)))



panel_z<-ggplot(coefs%>%filter(dataset=="Lake Washington : GAM"), aes(date, int_est, group = time_varying, fill=time_varying, col=time_varying)) + 
  geom_ribbon(aes(ymin=int_est-2*int_se, ymax = int_est+2*int_se), alpha=0.3, col = NA) + 
  geom_line(aes(lty=time_varying)) + 
  ylab("") + 
  xlab("") + theme_classic() + 
  ylim(-8.5,4.5)+
  ggtitle("GAM")+
  guides(fill="none")+
  scale_fill_manual(values=c(col[4],col[5]))+
  scale_colour_manual(values=c(col[4],col[5]))+
  labs(colour = "Time-Varying Parameter(s)", lty="Time-Varying Parameter(s)")+
  theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(hjust = 0.5),
    axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    legend.position = "bottom",
    legend.title = element_text(size = 12), # Adjust size for the legend title
    legend.text = element_text(size = 10) 
  )
panel_z

g_legend <- function(a.gplot){ 
  tmp <- ggplot_gtable(ggplot_build(a.gplot)) 
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box") 
  legend <- tmp$grobs[[leg]] 
  legend
} 

legend <- g_legend(panel_z) 

grid.newpage()
grid.draw(legend)

ggarrange(fig_left,fig_right, nrow=1,ncol=2)%>%
  annotate_figure(bottom = textGrob("Year",gp = gpar(cex =1)))%>%
  ggarrange(legend, nrow=2,ncol=1, heights=c(10,1))

ggsave("Figure_4_dlmgam_comparison.png", height = 5, width = 11, bg = "white")


```
