---
title: "gams_lakeWA"
format: docx
editor: visual
---

*Case Study 1: changing relationships in the Lake Washington food web*

*Data*

For our first case study, we apply Generalized Additive Models (GAMs) to a long term monitoring dataset collected from Lake Washington (Seattle, USA). Lake Washington is an urban lake that has been monitored since the 1950s; previous studies have documented the changing conditions in the lake resulting from urbanization and changing community structure (Edmundson 1970[\[EJW1\]](#_msocom_1) ; Francis et al. 2014[\[EJW2\]](#_msocom_2) ). One of the largest changes to the lake, and the focus of our case study is the relationship between phosphorous inputs and cyanobacteria blooms. In the mid 20^th^ century, the lake experienced declines in water qualitity and visibility, and high levels of cyanobacteria, in part because phosphorous from raw sewage inputs into the lake was high (Edmundson 1970). As sewage treatment plants were put in place through the 1960s, cyanobacteria levels were reduced and water quality improved. Since the 1970s, there have been additional documented changes, however for simplicity we focus on the changing relationship between phosphorous (driver) and cyanobacteria (response) over the early period, 1962 – 1973.  

We use GAMs for this case study, as they provide a flexible and accessible way to model relationships between covariates and predictors (Wood et al. 2011[\[EJW3\]](#_msocom_3) ; Pederson et al. 2019[\[EJW4\]](#_msocom_4) ), are accessible to many ecologists through the mgcv package in R (R Core Team 2024), and also allow us to contrast non-linearity with non-stationarity[\[EJW5\]](#_msocom_5) . To illustrate these ideas, we compare and contrast the three following models:

```{r eval=FALSE}
fit1 <- gam(cyan ~ s(phos, bs = "cr"), data = dat)
fit2 <- gam(cyan ~ s(phos, by = date, bs = "cr"), data = dat)
fit3 <- gam(cyan ~ s(date, by = phos, bs = "cr"), data = dat)
```

The first model, \`fit1\`, constructs a non-linear smooth (with "cr" denoting a cubic regression spline) on phosphorous as a predictor of cyanobacteria. This relationship includes a potential threshold effect, but is stationary because the relationship is fixed over the time series (plot in SI). Model 2 extends Mode 1 in also implementing a smooth over phosphorous to predict cyanobacteria, but differs in that the inclusion of "by = date" allows the smooth effect of phosphorous to vary by date. Model 3 looks similar to Model 2, but constructs a smooth over the "date" variable, and allows that to vary by different levels of phosphorous. Both Model 2 and Model 3 include non-linear effects, and non-stationarity, but importantly do so in different ways. Model 3 is more akin to a Dynamic Linear Model (DLM) with time-varying slope in modeling the smooth evolution of the trend through time, while Model 2 lets the phosphorous effect change over time (but not in a continuously smooth way). Model 3 could be extended to include a time-varying intercept by adding a smooth over date, "s(date)", but for this case study, we compare and contrast predictions and smooths from Models 2 and 3.
